### ISSUE TITLE
api-server: crash on launching container

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#1171]
**Describe the bug**

The API server crashes when the default configuration from the README is executed (fabric connector).

**To Reproduce**
Create CAS image: 
docker run \
  --rm \
  --publish 3000:3000 \
  --publish 4000:4000 \
  cas

then:

  docker run \
  --rm \
  --publish 3000:3000 \
  --publish 4000:4000 \
  cas \
    ./node_modules/.bin/cactusapi \
    --plugins='[{"packageName": "@hyperledger/cactus-plugin-ledger-connector-fabric", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL",  "options": { "connectionProfile": {}, "instanceId": "some-unique-instance-id"}}]'

**Expected behavior**

The API server runs without errors

**Logs/Stack traces**

rafael@x:~/Projects/Cactus/blockchain-integration-framework$   docker run \
>   --rm \
>   --publish 3000:3000 \
>   --publish 4000:4000 \
>   cas \
>     ./node_modules/.bin/cactusapi \
>     --plugins='[{"packageName": "@hyperledger/cactus-plugin-ledger-connector-fabric", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL",  "options": { "connectionProfile": {}, "instanceId": "some-unique-instance-id"}}]'

Warning: configuration param 'type' not declared in the schema
[2021-07-27T10:05:46.216Z] INFO (config-service): Configuration validation OK.
[2021-07-27T10:05:46.218Z] INFO (api-server): Setting tls.DEFAULT_MAX_VERSION to TLSv1.3...
[2021-07-27T10:05:46.219Z] INFO (api-server): wwwRoot: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www/
[2021-07-27T10:05:46.219Z] INFO (api-server): resolvedWwwRoot: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www
[2021-07-27T10:05:46.219Z] INFO (api-server): resolvedIndexHtml: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www/index.html
[2021-07-27T10:05:46.225Z] INFO (api-server): Cactus Cockpit net.AddressInfo { address: '0.0.0.0', family: 'IPv4', port: 3000 }
[2021-07-27T10:05:46.227Z] INFO (api-server): getOrInitPluginRegistry() initializing a new one...
[2021-07-27T10:05:46.227Z] INFO (api-server): Instantiated empty registry, invoking plugin factories...
[2021-07-27T10:05:46.227Z] INFO (api-server): Creating plugin from package: @hyperledger/cactus-plugin-ledger-connector-fabric { connectionProfile: {}, instanceId: 'some-unique-instance-id' }
[2021-07-27T10:05:46.228Z] INFO (api-server): Installing @hyperledger/cactus-plugin-ledger-connector-fabric for plugin import {
  packageName: '@hyperledger/cactus-plugin-ledger-connector-fabric',
  type: 'org.hyperledger.cactus.plugin_import_type.LOCAL',
  options: { connectionProfile: {}, instanceId: 'some-unique-instance-id' }
}
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fabric-network@1.4.17',
npm WARN EBADENGINE   required: { node: '^10.15.3 || ^12.15.0', npm: '^6.4.1' },
npm WARN EBADENGINE   current: { node: 'v12.20.1', npm: '7.8.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fabric-ca-client@1.4.17',
npm WARN EBADENGINE   required: { node: '^10.15.3 || ^12.15.0', npm: '^6.4.1' },
npm WARN EBADENGINE   current: { node: 'v12.20.1', npm: '7.8.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fabric-client@1.4.17',
npm WARN EBADENGINE   required: { node: '^10.15.3 || ^12.15.0', npm: ' ^6.4.1' },
npm WARN EBADENGINE   current: { node: 'v12.20.1', npm: '7.8.0' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated cloudant-follow@0.17.0: This package is no longer maintained.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated grpc@1.24.3: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.

added 242 packages, and removed 292 packages in 21s

8 packages are looking for funding
  run `npm fund` for details
[2021-07-27T10:06:07.203Z] INFO (api-server): Installed @hyperledger/cactus-plugin-ledger-connector-fabric OK undefined
[2021-07-27T10:06:07.651Z] ERROR (api-server): Failed to start ApiServer: Error: "PluginLedgerConnectorFabric#constructor() options.peerBinary" is falsy, need a truthy value.
    at Function.truthy (/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/node_modules/@hyperledger/cactus-common/dist/lib/main/typescript/checks.js:16:19)
    at new PluginLedgerConnectorFabric (/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/plugin-ledger-connector-fabric.js:42:32)
    at PluginFactoryLedgerConnector.create (/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/plugin-factory-ledger-connector.js:8:16)
    at ApiServer.initPluginRegistry (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js:171:48)
    at async ApiServer.getOrInitPluginRegistry (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js:146:39)
    at async ApiServer.startApiServer (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js:324:32)
    at async ApiServer.start (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js:93:36)
    at async main (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js:26:9)
    at async launchApp (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js:31:9)
[2021-07-27T10:06:07.651Z] ERROR (api-server): Attempting shutdown...
[2021-07-27T10:06:07.651Z] INFO (api-server): Shutting down API server ...
[2021-07-27T10:06:07.652Z] INFO (api-server): getOrInitPluginRegistry() initializing a new one...
[2021-07-27T10:06:07.652Z] INFO (api-server): Instantiated empty registry, invoking plugin factories...
[2021-07-27T10:06:07.652Z] INFO (api-server): Creating plugin from package: @hyperledger/cactus-plugin-ledger-connector-fabric { connectionProfile: {}, instanceId: 'some-unique-instance-id' }
[2021-07-27T10:06:07.652Z] INFO (api-server): Installing @hyperledger/cactus-plugin-ledger-connector-fabric for plugin import {
  packageName: '@hyperledger/cactus-plugin-ledger-connector-fabric',
  type: 'org.hyperledger.cactus.plugin_import_type.LOCAL',
  options: { connectionProfile: {}, instanceId: 'some-unique-instance-id' }
}
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fabric-network@1.4.17',
npm WARN EBADENGINE   required: { node: '^10.15.3 || ^12.15.0', npm: '^6.4.1' },
npm WARN EBADENGINE   current: { node: 'v12.20.1', npm: '7.8.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fabric-ca-client@1.4.17',
npm WARN EBADENGINE   required: { node: '^10.15.3 || ^12.15.0', npm: '^6.4.1' },
npm WARN EBADENGINE   current: { node: 'v12.20.1', npm: '7.8.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fabric-client@1.4.17',
npm WARN EBADENGINE   required: { node: '^10.15.3 || ^12.15.0', npm: ' ^6.4.1' },
npm WARN EBADENGINE   current: { node: 'v12.20.1', npm: '7.8.0' }
npm WARN EBADENGINE }

changed 1 package in 25s

8 packages are looking for funding
  run `npm fund` for details
[2021-07-27T10:06:10.878Z] INFO (api-server): Installed @hyperledger/cactus-plugin-ledger-connector-fabric OK undefined
[2021-07-27T10:06:10.879Z] ERROR (cactus-api): Cactus API server crashed:  CodedError: "PluginLedgerConnectorFabric#constructor() options.peerBinary" is falsy, need a truthy value.
    at Function.truthy (/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/node_modules/@hyperledger/cactus-common/dist/lib/main/typescript/checks.js:16:19)
    at new PluginLedgerConnectorFabric (/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/plugin-ledger-connector-fabric.js:42:32)
    at PluginFactoryLedgerConnector.create (/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/plugin-factory-ledger-connector.js:8:16)
    at ApiServer.initPluginRegistry (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js:171:48)
    at async ApiServer.getOrInitPluginRegistry (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js:146:39)
    at async ApiServer.shutdown (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js:224:26)
    at async ApiServer.start (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js:114:13)
    at async main (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js:26:9)
    at async launchApp (/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js:31:9) {
  code: '-1'
}
**Operating system name, version, build:**
bash: Linux 5.8.0-63-generic x86_64\nNAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

539a801d

**Additional context**

npm version 7.15.1
node version v16.3.0

**Comment by RafaelAPB** [comment]
This issue will be considered if the depending package remains, as part of the cleanup initiative: https://github.com/hyperledger-cacti/cacti/issues/4037
