### ISSUE TITLE
api-server: crash on launching container (with Besu Connector)

### ISSUE THREAD

**Issue by RafaelAPB** [hyperledger/cactus#1172]
Describe the bug

The API server crashes when the default configuration from the README is executed (fabric connector).

To Reproduce
Create CAS image:
docker run
--rm
--publish 3000:3000
--publish 4000:4000
cas

then:

  docker run \
  --rm \
  --publish 3000:3000 \
  --publish 4000:4000 \
  cas \
    ./node_modules/.bin/cactusapi \
    --plugins='[{"packageName": "@hyperledger/cactus-plugin-ledger-connector-fabric", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL",  "options": { "connectionProfile": {}, "instanceId": "some-unique-instance-id"}}]'

Expected behavior

The API server runs without errors

Logs/Stack traces

rafael@x:$ docker run \
>   --rm \
>   --publish 3000:3000 \
>   --publish 4000:4000 \
>   --env PLUGINS='[{"packageName": "@hyperledger/cactus-plugin-ledger-connector-besu", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL",  "options": {"rpcApiHttpHost": "http://localhost:8545", "instanceId": "some-unique-besu-connector-instance-id"}}]' \
>   cas

Warning: configuration param 'type' not declared in the schema
[2021-07-27T10:11:06.653Z] INFO (config-service): Configuration validation OK.
[2021-07-27T10:11:06.655Z] INFO (api-server): Setting tls.DEFAULT_MAX_VERSION to TLSv1.3...
[2021-07-27T10:11:06.655Z] INFO (api-server): wwwRoot: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www/
[2021-07-27T10:11:06.655Z] INFO (api-server): resolvedWwwRoot: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www
[2021-07-27T10:11:06.655Z] INFO (api-server): resolvedIndexHtml: /usr/src/app/node_modules/@hyperledger/cactus-cockpit/www/index.html
[2021-07-27T10:11:06.662Z] INFO (api-server): Cactus Cockpit net.AddressInfo { address: '0.0.0.0', family: 'IPv4', port: 3000 }
[2021-07-27T10:11:06.663Z] INFO (api-server): getOrInitPluginRegistry() initializing a new one...
[2021-07-27T10:11:06.664Z] INFO (api-server): Instantiated empty registry, invoking plugin factories...
[2021-07-27T10:11:06.664Z] INFO (api-server): Creating plugin from package: @hyperledger/cactus-plugin-ledger-connector-besu {
  rpcApiHttpHost: 'http://localhost:8545',
  instanceId: 'some-unique-besu-connector-instance-id'
}
[2021-07-27T10:11:06.664Z] INFO (api-server): Installing @hyperledger/cactus-plugin-ledger-connector-besu for plugin import {
  packageName: '@hyperledger/cactus-plugin-ledger-connector-besu',
  type: 'org.hyperledger.cactus.plugin_import_type.LOCAL',
  options: {
    rpcApiHttpHost: 'http://localhost:8545',
    instanceId: 'some-unique-besu-connector-instance-id'
  }
}
npm WARN deprecated uuid@2.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated @web3-js/scrypt-shim@0.1.0: This package is deprecated, for a pure JS implementation please use scrypt-js
npm WARN deprecated @web3-js/websocket@1.0.30: The branch for this fork was merged upstream, please update your package to websocket@1.0.31
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

added 277 packages, and removed 310 packages in 21s

4 packages are looking for funding
  run `npm fund` for details
[2021-07-27T10:11:27.327Z] INFO (api-server): Installed @hyperledger/cactus-plugin-ledger-connector-besu OK undefined
[2021-07-27T10:11:27.422Z] ERROR (api-server): Failed to start ApiServer: Error: Cannot find module 'bluebird'
Require stack:
- /usr/src/app/node_modules/swarm-js/lib/files.js
- /usr/src/app/node_modules/swarm-js/lib/api-node.js
- /usr/src/app/node_modules/web3-bzz/src/index.js
- /usr/src/app/node_modules/web3/src/index.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/plugin-ledger-connector-besu.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/public-api.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/index.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/swarm-js/lib/files.js:5:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
[2021-07-27T10:11:27.422Z] ERROR (api-server): Attempting shutdown...
[2021-07-27T10:11:27.422Z] INFO (api-server): Shutting down API server ...
[2021-07-27T10:11:27.422Z] INFO (api-server): getOrInitPluginRegistry() initializing a new one...
[2021-07-27T10:11:27.423Z] INFO (api-server): Instantiated empty registry, invoking plugin factories...
[2021-07-27T10:11:27.423Z] INFO (api-server): Creating plugin from package: @hyperledger/cactus-plugin-ledger-connector-besu {
  rpcApiHttpHost: 'http://localhost:8545',
  instanceId: 'some-unique-besu-connector-instance-id'
}
[2021-07-27T10:11:27.423Z] INFO (api-server): Installing @hyperledger/cactus-plugin-ledger-connector-besu for plugin import {
  packageName: '@hyperledger/cactus-plugin-ledger-connector-besu',
  type: 'org.hyperledger.cactus.plugin_import_type.LOCAL',
  options: {
    rpcApiHttpHost: 'http://localhost:8545',
    instanceId: 'some-unique-besu-connector-instance-id'
  }
}

changed 1 package in 24s

4 packages are looking for funding
  run `npm fund` for details
[2021-07-27T10:11:30.475Z] INFO (api-server): Installed @hyperledger/cactus-plugin-ledger-connector-besu OK undefined
[2021-07-27T10:11:30.478Z] ERROR (cactus-api): Cactus API server crashed:  Error: Cannot find module 'bluebird'
Require stack:
- /usr/src/app/node_modules/swarm-js/lib/files.js
- /usr/src/app/node_modules/swarm-js/lib/api-node.js
- /usr/src/app/node_modules/web3-bzz/src/index.js
- /usr/src/app/node_modules/web3/src/index.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/plugin-ledger-connector-besu.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/public-api.js
- /usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/index.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js
- /usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/node_modules/swarm-js/lib/files.js:5:9)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/node_modules/swarm-js/lib/files.js',
    '/usr/src/app/node_modules/swarm-js/lib/api-node.js',
    '/usr/src/app/node_modules/web3-bzz/src/index.js',
    '/usr/src/app/node_modules/web3/src/index.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/plugin-ledger-connector-besu.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/public-api.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-plugin-ledger-connector-besu/dist/lib/main/typescript/index.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/api-server.js',
    '/usr/src/app/node_modules/@hyperledger/cactus-cmd-api-server/dist/lib/main/typescript/cmd/cactus-api.js'
  ]
}

Operating system name, version, build:
bash: Linux 5.8.0-63-generic x86_64\nNAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal

Hyperledger Cactus release version or commit (git rev-parse --short HEAD):

539a801

Additional context

npm version 7.15.1
node version v16.3.0

**Comment by elenaizaguirre** [comment]
@petermetz Can this issue be the same as #840?

**Comment by petermetz** [comment]
@elenaizaguirre Yes, I think they are the same now that you mention it.
@RafaelAPB Have you tested this ever since it was reported? (it should be fixed by now but please reopen it if it's not the case)
