### ISSUE TITLE
test(test-tooling): fix flaky rustc-container-target-nodejs.test

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#1646]
Marking this as a good first issue because most likely it's due to some race condition
in the code that someone with sufficient general knowledge of programming should be
able to debug with little knowledge/understanding about the architecture of Cactus
as a whole.

The path of the test file is:
`packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-nodejs.test.ts`

## Logs

Full CI logs archive: [logs_11827.zip](https://github.com/hyperledger/cactus/files/7678953/logs_11827.zip)

It passes fine most of the time, but every now and then it fails with logs like this:

```sh
2021-12-08T05:46:29.9872651Z 
2021-12-08T05:51:34.8397514Z FAIL packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-nodejs.test.ts (312.72 s)
2021-12-08T05:51:34.8468546Z   ● Console
2021-12-08T05:51:34.8469295Z 
2021-12-08T05:51:34.8470197Z     console.log
2021-12-08T05:51:34.8471691Z       [2021-12-08T05:46:28.662Z] DEBUG (RustcContainer): Created instance of RustcContainer OK
2021-12-08T05:51:34.8472203Z 
2021-12-08T05:51:34.8473384Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8474072Z 
2021-12-08T05:51:34.8474412Z     console.log
2021-12-08T05:51:34.8475465Z       [2021-12-08T05:46:28.682Z] DEBUG (RustcContainer): Pulling image ghcr.io/hyperledger/cactus-rust-compiler:1.0.3...
2021-12-08T05:51:34.8476061Z 
2021-12-08T05:51:34.8477071Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8477757Z 
2021-12-08T05:51:34.8478102Z     console.log
2021-12-08T05:51:34.8479275Z       [2021-12-08T05:46:29.100Z] DEBUG (containers#tryPullImage()): Started ghcr.io/hyperledger/cactus-rust-compiler:1.0.3 pull progress stream OK
2021-12-08T05:51:34.8479962Z 
2021-12-08T05:51:34.8481012Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8481695Z 
2021-12-08T05:51:34.8482029Z     console.log
2021-12-08T05:51:34.8483059Z       [2021-12-08T05:46:29.122Z] DEBUG (containers#tryPullImage()): "Pulling from hyperledger/cactus-rust-compiler"
2021-12-08T05:51:34.8483650Z 
2021-12-08T05:51:34.8484695Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8485377Z 
2021-12-08T05:51:34.8485726Z     console.log
2021-12-08T05:51:34.8486680Z       [2021-12-08T05:46:30.123Z] DEBUG (containers#tryPullImage()): "[==========>                                        ]  40.03MB/195.5MB"
2021-12-08T05:51:34.8487102Z 
2021-12-08T05:51:34.8488163Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8488855Z 
2021-12-08T05:51:34.8489240Z     console.log
2021-12-08T05:51:34.8490182Z       [2021-12-08T05:46:31.125Z] DEBUG (containers#tryPullImage()): "[=============================================>     ]  178.6MB/195.5MB"
2021-12-08T05:51:34.8490645Z 
2021-12-08T05:51:34.8491692Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8492385Z 
2021-12-08T05:51:34.8492745Z     console.log
2021-12-08T05:51:34.8493666Z       [2021-12-08T05:46:32.194Z] DEBUG (containers#tryPullImage()): "[=>                                                 ]  5.571MB/195.5MB"
2021-12-08T05:51:34.8494100Z 
2021-12-08T05:51:34.8495165Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8495856Z 
2021-12-08T05:51:34.8496195Z     console.log
2021-12-08T05:51:34.8497956Z       [2021-12-08T05:46:33.197Z] DEBUG (containers#tryPullImage()): "[=======>                                           ]  28.41MB/195.5MB"
2021-12-08T05:51:34.8498407Z 
2021-12-08T05:51:34.8499477Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8500338Z 
2021-12-08T05:51:34.8500711Z     console.log
2021-12-08T05:51:34.8501689Z       [2021-12-08T05:46:34.202Z] DEBUG (containers#tryPullImage()): "[===================>                               ]  75.76MB/195.5MB"
2021-12-08T05:51:34.8502123Z 
2021-12-08T05:51:34.8503244Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8503957Z 
2021-12-08T05:51:34.8504296Z     console.log
2021-12-08T05:51:34.8505236Z       [2021-12-08T05:46:35.203Z] DEBUG (containers#tryPullImage()): "[=============================>                     ]  114.2MB/195.5MB"
2021-12-08T05:51:34.8505671Z 
2021-12-08T05:51:34.8506744Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8507455Z 
2021-12-08T05:51:34.8507815Z     console.log
2021-12-08T05:51:34.8508754Z       [2021-12-08T05:46:36.231Z] DEBUG (containers#tryPullImage()): "[========================================>          ]  158.2MB/195.5MB"
2021-12-08T05:51:34.8509184Z 
2021-12-08T05:51:34.8510493Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8513936Z 
2021-12-08T05:51:34.8514351Z     console.log
2021-12-08T05:51:34.8515505Z       [2021-12-08T05:46:37.232Z] DEBUG (containers#tryPullImage()): "[==================================================>]  195.5MB/195.5MB"
2021-12-08T05:51:34.8515930Z 
2021-12-08T05:51:34.8516943Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8517625Z 
2021-12-08T05:51:34.8517977Z     console.log
2021-12-08T05:51:34.8518764Z       [2021-12-08T05:46:39.037Z] DEBUG (containers#tryPullImage()): "Pull complete"
2021-12-08T05:51:34.8519208Z 
2021-12-08T05:51:34.8520229Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8520896Z 
2021-12-08T05:51:34.8521225Z     console.log
2021-12-08T05:51:34.8522119Z       [2021-12-08T05:46:40.037Z] DEBUG (containers#tryPullImage()): "[===================>                               ]  20.45MB/51.15MB"
2021-12-08T05:51:34.8522539Z 
2021-12-08T05:51:34.8523542Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8524217Z 
2021-12-08T05:51:34.8524565Z     console.log
2021-12-08T05:51:34.8525422Z       [2021-12-08T05:46:41.041Z] DEBUG (containers#tryPullImage()): "[=================================================> ]  50.86MB/51.15MB"
2021-12-08T05:51:34.8525843Z 
2021-12-08T05:51:34.8526856Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8527537Z 
2021-12-08T05:51:34.8583151Z     console.log
2021-12-08T05:51:34.8584645Z       [2021-12-08T05:46:42.041Z] DEBUG (containers#tryPullImage()): "[>                                                  ]  557.1kB/102.8MB"
2021-12-08T05:51:34.8585082Z 
2021-12-08T05:51:34.8586158Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8586839Z 
2021-12-08T05:51:34.8587196Z     console.log
2021-12-08T05:51:34.8588068Z       [2021-12-08T05:46:43.058Z] DEBUG (containers#tryPullImage()): "[===========================================>       ]  89.13MB/102.8MB"
2021-12-08T05:51:34.8588486Z 
2021-12-08T05:51:34.8589552Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8590224Z 
2021-12-08T05:51:34.8590557Z     console.log
2021-12-08T05:51:34.8591452Z       [2021-12-08T05:46:44.094Z] DEBUG (containers#tryPullImage()): "[===============================================>   ]  96.93MB/102.8MB"
2021-12-08T05:51:34.8592343Z 
2021-12-08T05:51:34.8593366Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8594042Z 
2021-12-08T05:51:34.8594393Z     console.log
2021-12-08T05:51:34.8595390Z       [2021-12-08T05:46:45.099Z] DEBUG (containers#tryPullImage()): "[==================================================>]  102.8MB/102.8MB"
2021-12-08T05:51:34.8595813Z 
2021-12-08T05:51:34.8596837Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8597513Z 
2021-12-08T05:51:34.8597844Z     console.log
2021-12-08T05:51:34.8598636Z       [2021-12-08T05:46:45.699Z] DEBUG (containers#tryPullImage()): "Pull complete"
2021-12-08T05:51:34.8599060Z 
2021-12-08T05:51:34.8600062Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8600737Z 
2021-12-08T05:51:34.8601090Z     console.log
2021-12-08T05:51:34.8602224Z       [2021-12-08T05:46:45.705Z] DEBUG (containers#tryPullImage()): Finished ghcr.io/hyperledger/cactus-rust-compiler:1.0.3 pull completely OK
2021-12-08T05:51:34.8602894Z 
2021-12-08T05:51:34.8603913Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8604589Z 
2021-12-08T05:51:34.8604918Z     console.log
2021-12-08T05:51:34.8605933Z       [2021-12-08T05:46:45.706Z] DEBUG (RustcContainer): Pulled image ghcr.io/hyperledger/cactus-rust-compiler:1.0.3 OK
2021-12-08T05:51:34.8606523Z 
2021-12-08T05:51:34.8607524Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8608198Z 
2021-12-08T05:51:34.8608543Z     console.log
2021-12-08T05:51:34.8609590Z       [2021-12-08T05:46:45.706Z] DEBUG (RustcContainer): Starting ghcr.io/hyperledger/cactus-rust-compiler:1.0.3 with options:  {
2021-12-08T05:51:34.8610650Z         WorkingDir: '/usr/src/host-sources-dir/',
2021-12-08T05:51:34.8611121Z         Env: [],
2021-12-08T05:51:34.8611510Z         Healthcheck: {
2021-12-08T05:51:34.8611901Z           Test: [
2021-12-08T05:51:34.8612390Z             'CMD-SHELL',
2021-12-08T05:51:34.8613111Z             'rustup --version && rustc --version && cargo --version'
2021-12-08T05:51:34.8613582Z           ],
2021-12-08T05:51:34.8613958Z           Interval: 1000000000,
2021-12-08T05:51:34.8614366Z           Timeout: 3000000000,
2021-12-08T05:51:34.8614752Z           Retries: 10,
2021-12-08T05:51:34.8615179Z           StartPeriod: 1000000000
2021-12-08T05:51:34.8615539Z         },
2021-12-08T05:51:34.8616021Z         HostConfig: { AutoRemove: true, Binds: [] }
2021-12-08T05:51:34.8616442Z       }
2021-12-08T05:51:34.8616656Z 
2021-12-08T05:51:34.8632372Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8633129Z 
2021-12-08T05:51:34.8633482Z     console.log
2021-12-08T05:51:34.8635558Z       [2021-12-08T05:46:45.988Z] DEBUG (RustcContainer): Started ghcr.io/hyperledger/cactus-rust-compiler:1.0.3 successfully. ID=23aa7af045225cfc5b3c8fbda68dfd5a81e1ec3ffb9936d14f93f138f657938c
2021-12-08T05:51:34.8636785Z 
2021-12-08T05:51:34.8637812Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8638520Z 
2021-12-08T05:51:34.8638892Z     console.log
2021-12-08T05:51:34.8639771Z       [2021-12-08T05:46:45.991Z] DEBUG (RustcContainer): Registered container log stream callbacks OK
2021-12-08T05:51:34.8640274Z 
2021-12-08T05:51:34.8641297Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8641977Z 
2021-12-08T05:51:34.8642309Z     console.log
2021-12-08T05:51:34.8643147Z       [2021-12-08T05:46:45.991Z] DEBUG (RustcContainer): Starting to wait for healthcheck...
2021-12-08T05:51:34.8643604Z 
2021-12-08T05:51:34.8644609Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8645549Z 
2021-12-08T05:51:34.8645900Z     console.log
2021-12-08T05:51:34.8647078Z       [2021-12-08T05:46:46.699Z] DEBUG (containers#tryPullImage()): "Status: Downloaded newer image for ghcr.io/hyperledger/cactus-rust-compiler:1.0.3"
2021-12-08T05:51:34.8647876Z 
2021-12-08T05:51:34.8648920Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8649596Z 
2021-12-08T05:51:34.8649930Z     console.log
2021-12-08T05:51:34.8650711Z       [2021-12-08T05:46:49.010Z] DEBUG (RustcContainer): Healthcheck passed OK
2021-12-08T05:51:34.8651133Z 
2021-12-08T05:51:34.8652129Z       at Logger.<anonymous> (node_modules/loglevel-plugin-prefix/lib/loglevel-plugin-prefix.js:106:24)
2021-12-08T05:51:34.8652802Z 
2021-12-08T05:51:34.8653811Z   ● compiles Rust code to NodeJS targeted .wasm › compiles Rust code to NodeJS targeted .wasm
2021-12-08T05:51:34.8654305Z 
2021-12-08T05:51:34.8654823Z     expect(received).toEqual(expected) // deep equality
2021-12-08T05:51:34.8655220Z 
2021-12-08T05:51:34.8655690Z     - Expected  - 5
2021-12-08T05:51:34.8656069Z     + Received  + 0
2021-12-08T05:51:34.8656318Z 
2021-12-08T05:51:34.8656635Z       Array [
2021-12-08T05:51:34.8657001Z         ".gitignore",
2021-12-08T05:51:34.8658455Z     -   "hello_world.d.ts",
2021-12-08T05:51:34.8659028Z     -   "hello_world.js",
2021-12-08T05:51:34.8659575Z     -   "hello_world_bg.wasm",
2021-12-08T05:51:34.8660182Z     -   "hello_world_bg.wasm.d.ts",
2021-12-08T05:51:34.8660752Z     -   "package.json",
2021-12-08T05:51:34.8661124Z       ]
2021-12-08T05:51:34.8661334Z 
2021-12-08T05:51:34.8661782Z       94 |     expect(filesOnFs).toBeTruthy();
2021-12-08T05:51:34.8662421Z       95 |     expect(Array.isArray(filesOnFs)).toBe(true);
2021-12-08T05:51:34.8663093Z     > 96 |     expect(filesOnFs).toEqual(expectedFiles);
2021-12-08T05:51:34.8663621Z          |                       ^
2021-12-08T05:51:34.8663968Z       97 |
2021-12-08T05:51:34.8664498Z       98 |     const fileChecks = filesOnFs.map(async (fileName) => {
2021-12-08T05:51:34.8665346Z       99 |       const containerFilePath = path.join(containerPkDir, fileName);
2021-12-08T05:51:34.8665848Z 
2021-12-08T05:51:34.8667242Z       at Object.<anonymous> (packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-nodejs.test.ts:96:23)
2021-12-08T05:51:34.8668465Z           at runMicrotasks (<anonymous>)
2021-12-08T05:51:34.8668788Z 
```

```sh
2021-12-08T05:54:55.7496373Z Summary of all failing tests
2021-12-08T05:54:55.7503536Z FAIL packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-nodejs.test.ts (312.72 s)
2021-12-08T05:54:55.7505502Z   ● compiles Rust code to NodeJS targeted .wasm › compiles Rust code to NodeJS targeted .wasm
2021-12-08T05:54:55.7506256Z 
2021-12-08T05:54:55.7506958Z     expect(received).toEqual(expected) // deep equality
2021-12-08T05:54:55.7507534Z 
2021-12-08T05:54:55.7508244Z     - Expected  - 5
2021-12-08T05:54:55.7508835Z     + Received  + 0
2021-12-08T05:54:55.7509263Z 
2021-12-08T05:54:55.7509769Z       Array [
2021-12-08T05:54:55.7510312Z         ".gitignore",
2021-12-08T05:54:55.7511055Z     -   "hello_world.d.ts",
2021-12-08T05:54:55.7511817Z     -   "hello_world.js",
2021-12-08T05:54:55.7512580Z     -   "hello_world_bg.wasm",
2021-12-08T05:54:55.7513387Z     -   "hello_world_bg.wasm.d.ts",
2021-12-08T05:54:55.7514213Z     -   "package.json",
2021-12-08T05:54:55.7514763Z       ]
2021-12-08T05:54:55.7515149Z 
2021-12-08T05:54:55.7515801Z       94 |     expect(filesOnFs).toBeTruthy();
2021-12-08T05:54:55.7516609Z       95 |     expect(Array.isArray(filesOnFs)).toBe(true);
2021-12-08T05:54:55.7518110Z     > 96 |     expect(filesOnFs).toEqual(expectedFiles);
2021-12-08T05:54:55.7518806Z          |                       ^
2021-12-08T05:54:55.7519257Z       97 |
2021-12-08T05:54:55.7519923Z       98 |     const fileChecks = filesOnFs.map(async (fileName) => {
2021-12-08T05:54:55.7520928Z       99 |       const containerFilePath = path.join(containerPkDir, fileName);
2021-12-08T05:54:55.7521540Z 
2021-12-08T05:54:55.7523128Z       at Object.<anonymous> (packages/cactus-test-tooling/src/test/typescript/integration/rustc-container/rustc-container-target-nodejs.test.ts:96:23)
2021-12-08T05:54:55.7529444Z           at runMicrotasks (<anonymous>)
2021-12-08T05:54:55.7530052Z 
2021-12-08T05:54:55.7530377Z 
2021-12-08T05:54:55.7531049Z Test Suites: 1 failed, 77 passed, 78 total
2021-12-08T05:54:55.7531761Z Tests:       1 failed, 105 passed, 106 total
2021-12-08T05:54:55.7532748Z Snapshots:   0 total
2021-12-08T05:54:55.7533270Z Time:        850.936 s
2021-12-08T05:54:55.7533795Z Ran all test suites.
```

## Version

`1.0.0-rc.3`

**Comment by petermetz** [comment]
Inspecting the cargo / wasm-pack build output logs with the debugger offered some clues:

```sh
wasmPackBuildOut
'[INFO]: Checking for the Wasm target...
info: (Bdownloading component 'rust-std' for 'wasm32-unknown-unknown'
info: (Binstalling component 'rust-std' for 'wasm32-unknown-unknown'
info: (Busing up to 500.0 MiB of RAM to unpack components

  6.9 MiB /  13.2 MiB ( 53 %)   0 B/s in  1s ETA: Unknown
                                                         
  9.8 MiB /  13.2 MiB ( 74 %)   6.9 MiB/s in  2s ETA:  0s
                                                         
 13.2 MiB /  13.2 MiB (100 %)   4.9 MiB/s in  2s ETA:  0s
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling log v0.4.14
   Compiling wasm-bindgen-shared v0.2.78
   Compiling syn v1.0.85
   Compiling cfg-if v1.0.0
   Compiling lazy_static v1.4.0
   Compiling bumpalo v3.9.1
[38;5;9merror[E0658]: arbitrary expressions in key-value attributes are unstable
 [38;5;12m--> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bumpalo-3.9.1/src/lib.rs:1:10
  [38;5;12m|
[38;5;12m1 [38;5;12m| #![doc = include_str!("../README.md")]
  [38;5;12m|          [38;5;9m^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [38;5;12m|
  [38;5;12m= note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling wasm-bindgen v0.2.78
[38;5;9merror: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `bumpalo`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
'

```
