### ISSUE TITLE
instantiate proposal resulted in an error

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#52]
Doesn't always happen. When it does this is how it goes:

```sh
cd examples/simple-asset-transfer/

$ npm run fabric

> @hyperledger-labs/blockchain-integration-framework.examples.simple-asset-transfer@0.1.0 fabric /REDACTED/blockchain-integration-framework/examples/simple-asset-transfer
> cd fabric/scripts && ./start.sh

4000/tcp:            12171

Stopping peer1.org1.example.com ... done
Stopping peer0.org2.example.com ... done
Stopping peer1.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping ca_peerOrg2            ... done
Stopping ca_peerOrg1            ... done
Stopping orderer.example.com    ... done
Removing peer1.org1.example.com ... done
Removing peer0.org2.example.com ... done
Removing peer1.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca_peerOrg2            ... done
Removing ca_peerOrg1            ... done
Removing orderer.example.com    ... done
Removing network artifacts_default

ece5fece7250
51399562d912
f8622986b858
a81365dff541


Untagged: dev-peer0.org2.example.com-mycc-v1-355c3869dbdeb00af7c2dfeb05990f0fe3b1e87eb7a494ddec689e468087df2f:latest
Deleted: sha256:78bcd3ae860fa8cfe85524816237bb446101dffb7b9ecd61ead52c12cfd5762e
Deleted: sha256:edb8e174e95df0d4a6e59bd183206ee1bb1fbfdd8cceb8ae121ad06668e2d38f
Deleted: sha256:6bad450d8e5a09d301477f297c1615583f4d354edba6871676b9a0d7a6cfaf56
Deleted: sha256:47b25f3399230b05afa47c40c29657038ffe58a8b6705c612292ca5fb75317d3
Untagged: dev-peer1.org2.example.com-mycc-v1-d2bedf8545a99e60c83dff6b233903d5339e006f3c73b6b598611ac8ecceeea1:latest
Deleted: sha256:b33a905b1b6aeb608abebf433f0ccbe436a6b832eae28f316b343a6b06380c3e
Deleted: sha256:57de8f14f35c2c1d7d049d9384bd4be06255ef7d5818af9366341dbcc427b378
Deleted: sha256:1ac81559b9d6e7ba10e4569807c992f8679fd6b71aba48c97c90de0748003420
Deleted: sha256:c8198bebbf73f82af98604991f2c015f8380f28f9e268b99a0b3414530fe4a7b
Untagged: dev-peer0.org1.example.com-mycc-v1-2e8aae988c044f8defc1f175963163be4afda372a371605758993dbcd58f0411:latest
Deleted: sha256:ebefd1db6277fbfa43b15b5420db2a0757b2fef5714d988872256d125d359933
Deleted: sha256:1f997ce912c11570b4cd1c1a803ab8488563e889fd7c6bd93717673bc8201d43
Deleted: sha256:526989f9d6ee38645c7378fba21134495fa71870ff8710d6672c3b6d72c26565
Deleted: sha256:d17ea48c834c486ade174a8a5d8fabfa7d169988552e50c455e40bac5cd18d50
Untagged: dev-peer1.org1.example.com-mycc-v1-44e5460ab42b5b6dc9bbe3754df0e6d53c8cbd3ee340c3b5c41e86483014e2cb:latest
Deleted: sha256:b1cc0d8425ca5b6089ba24ced2c50b2139dcec682d503fb2dcd98a98ba4164d8
Deleted: sha256:0a78f2c479b71586bab48438d1a63b8cfe2e6f5386025c9c9fc9d4083cbfd89d
Deleted: sha256:ef2477285bf7db037e024e9400eb049b30cd6ba748f7e2b1a47174378e078cdd
Deleted: sha256:0110ca36ba5d3b814816e85c7e1f00b65b2759aaf42a7671fe679c32a653959e

Creating network "artifacts_default" with the default driver
Creating ca_peerOrg2            ... done
Creating orderer.example.com ... done
Creating ca_peerOrg1            ... done
Creating peer1.org1.example.com ... done
Creating peer0.org2.example.com ... done
Creating peer1.org2.example.com ... done
Creating peer0.org1.example.com ... done


============== Installing node modules =============
audited 22795 packages in 16.688s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

Starting the SDK server ... /REDACTED/blockchain-integration-framework/examples/simple-asset-transfer/fabric/scripts
5537
Initializing the network ...
[2019-11-15T11:32:53.827] [INFO] init-network - Naima enrolled Successfully
[2019-11-15T11:32:54.226] [INFO] init-network - Mike enrolled Successfully
[2019-11-15T11:32:54.962] [INFO] init-network - Hugo enrolled Successfully
[2019-11-15T11:32:55.443] [INFO] init-network - Luca enrolled Successfully
[2019-11-15T11:32:55.626] [INFO] init-network - Channel 'mychannel' created Successfully
[2019-11-15T11:33:05.718] [INFO] init-network - Successfully joined peers in organization Org1 to the channel:mychannel
[2019-11-15T11:33:05.983] [INFO] init-network - Successfully installed chaincode
[2019-11-15T11:33:16.032] [INFO] init-network - Successfully joined peers in organization Org2 to the channel:mychannel
[2019-11-15T11:33:16.256] [INFO] init-network - Successfully installed chaincode
[2019-11-15T11:34:24.316] [ERROR] init-network - Error: Failed to instantiate the chaincode. cause:instantiate proposal resulted in an error :: Error: error starting container: error starting container: Failed to generate platform-specific docker build: Error executing build: API error (500): ttrpc: closed: unknown ""
    at /REDACTED/blockchain-integration-framework/examples/simple-asset-transfer/fabric/scripts/init-network.js:145:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger-labs/blockchain-integration-framework.examples.simple-asset-transfer@0.1.0 fabric: `cd fabric/scripts && ./start.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @hyperledger-labs/blockchain-integration-framework.examples.simple-asset-transfer@0.1.0 fabric script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/multipass/.npm/_logs/2019-11-15T19_34_24_329Z-debug.log
npm ERR! path /REDACTED/blockchain-integration-framework/examples/simple-asset-transfer/quorum/api/node_modules/websocket
npm ERR! code EISGIT
npm ERR! git /REDACTED/blockchain-integration-framework/examples/simple-asset-transfer/quorum/api/node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git     /REDACTED/blockchain-integration-framework/examples/simple-asset-transfer/quorum/api/node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/multipass/.npm/_logs/2019-11-15T19_34_35_411Z-debug.log

```

**Comment by petermetz** [comment]
Fixed by #123
