### ISSUE TITLE
panic: MustNew: Failed to connect to Constellation

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cactus#68]
**Describe the bug**

CI script fails in a new way never seen before.
Testing on a VM mimicking Travis CI's VM: 8GB RAM, 2 vCPUs

The weird thing is that we don't use constellation but tessera, so where did it get Constellation from in the panic message?

**To Reproduce**

Run `ci.sh`, see as it fails, then do `docker logs $FIRST_QUORUM_NODE_CONTAINER_ID`
And observe that it was waiting for the tx manager to come online for a long time and then panicked with an error.

**Expected behavior**

CI script doesn't fail.

**Logs**

```sh
Waiting for the tx manager to start...
still waiting for the tx manager (1)...
still waiting for the tx manager (2)...
still waiting for the tx manager (3)...
still waiting for the tx manager (4)...
still waiting for the tx manager (5)...
still waiting for the tx manager (6)...
still waiting for the tx manager (7)...
still waiting for the tx manager (8)...
still waiting for the tx manager (9)...
still waiting for the tx manager (10)...
still waiting for the tx manager (11)...
still waiting for the tx manager (12)...
still waiting for the tx manager (13)...
still waiting for the tx manager (14)...
still waiting for the tx manager (15)...
panic: MustNew: Failed to connect to Constellation (/qdata/tm/tm.ipc): Get http+unix://c/upcheck: read unix @->/qdata/tm/tm.ipc: i/o timeout

goroutine 1 [running]:
github.com/ethereum/go-ethereum/private/constellation.MustNew(0xc00003600f, 0x10, 0xc00003600f)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:108 +0x1de
github.com/ethereum/go-ethereum/private.FromEnvironmentOrNil(0x110f1f2, 0xe, 0xc0001f15e0, 0xc0001f15c0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:20 +0x64
panic: MustNew: Failed to connect to Constellation (/qdata/tm/tm.ipc): Get http+unix://c/upcheck: read unix @->/qdata/tm/tm.ipc: i/o timeout

goroutine 1 [running]:
github.com/ethereum/go-ethereum/private/constellation.MustNew(0xc00003600f, 0x10, 0xc00003600f)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:108 +0x1de
github.com/ethereum/go-ethereum/private.FromEnvironmentOrNil(0x110f1f2, 0xe, 0xc000220bc0, 0xc000220ba0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:20 +0x64
```

**Cloud provider or hardware configuration:**
Dev machine

**Operating system name, version, build:**

```sh
Linux 4.15.0-70-generic x86_64
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**BIF release version or commit (git rev-parse --short HEAD):**

`87e0c09`

**Comment by petermetz** [comment]
Fixed by #123 with the help of the all in one quorum image this is no longer a problem.
