### ISSUE TITLE
fix(readthedocsio): failing the build in readthedocsio site

### ISSUE THREAD

**Issue by AzaharaC** [hyperledger/cactus#981]
**Is your feature request related to a problem? Please describe.**

The latest version of readthedocs fails to build with the following error:

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hyperledger-cactus/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'sphinx_markdown_tables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/hyperledger-cactus/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hyperledger-cactus/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hyperledger-cactus/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/hyperledger-cactus/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_markdown_tables (exception: No module named 'sphinx_markdown_tables')

Extension error:
Could not import extension sphinx_markdown_tables (exception: No module named 'sphinx_markdown_tables')
Command time: 0s Return: 2
```

**Acceptance Criteria**
When the build of the latest version is executed it should have a successful result.

**Comment by AzaharaC** [comment]
@petermetz I have found three possible solutions to the problem:
- The first, in the readthedoc configuration file, there is a line that makes the compilation fail if there is a warning. (I have deleted this line)
- Another option is to add this to the configuration file:
```
python:
  version: 3.7
  install:
    - requirements: docs/pip-requirements.txt
```
- The third option can be to change this line ```sphinx_markdown_tables``` in the pip-requirements.txt file for this other one ``` sphinx-markdown-tables``` (but locally it works with the current line)

I have done a PR with the first two options, which I think are the ones that will solve the error.

**Comment by petermetz** [comment]
@AzaharaC Awesome analysis, thank you! Let's see how it works out once you also push your branch to the upstream remote (let me know if need help with the git stuff)

**Comment by AzaharaC** [comment]
@petermetz  I put my branch to the remote upstream and used it to build the version in readthedocs. I confirm that the changes work. I have put the PR (#1004) as ready for review.
